export const FONTS = [
  { family: 'Abril Fatface',      weight: 400 },
  { family: 'Dancing Script',     weight: 700 },
  { family: 'Playfair Display',   weight: 700 },
  { family: 'Roboto Slab',        weight: 700 },
  { family: 'Nunito',             weight: 700 },
  { family: 'DM Sans',            weight: 700 },
  { family: 'Space Mono',         weight: 700 },
  { family: 'Caveat',             weight: 700 },
  { family: 'Bebas Neue',         weight: 400 },
  { family: 'Anton',              weight: 400 },
  { family: 'Permanent Marker',   weight: 400 },
  { family: 'Lobster',            weight: 400 },
  { family: 'Bungee',             weight: 400 },
  { family: 'Fraunces',           weight: 700 },
  { family: 'Archivo Black',      weight: 400 },
]
